import type { MediaAsset, NovelProject } from './types'

const kiroLifeLooks = [
  ['01', '春季校园基础装', ['春季', '校园']],
  ['02', '图书馆阅读装', ['图书馆', '阅读']],
  ['03', '泳后日常装', ['夏季', '泳后', '日常']],
  ['04', 'AI 实验室装', ['AI 实验室', '科技']],
  ['05', '雨天街道装', ['雨天', '街道']],
  ['06', '雪天图书馆装', ['冬季', '雪天', '图书馆']],
  ['07', '深炭灰高领 + 冷灰蓝背心裙', ['冷色穿搭', '背心裙']],
  ['08', '墨灰半高领 + 黑色短西装', ['冷色穿搭', '通勤']],
  ['09', '石墨灰圆领 + 冷灰蓝衬衫外搭', ['冷色穿搭', '叠穿']],
  ['10', '黑色极简衬衫连衣裙', ['极简', '连衣裙']],
  ['11', '夏日湖边海边旅行装', ['夏季', '旅行', '湖边', '海边']],
  ['12', '夏夜写作装', ['夏季', '夜晚', '写作']],
  ['13', 'AI 实验室变体装', ['AI 实验室', '科技', '变体']],
  ['14', '雨天街道变体装', ['雨天', '街道', '变体']],
  ['15', '古城历史旅行装', ['旅行', '古城', '历史']],
  ['16', '秋日校园阅读装', ['秋季', '校园', '阅读']],
  ['17', '雪天图书馆变体装', ['冬季', '雪天', '图书馆', '变体']],
  ['18', '冬日通学装', ['冬季', '通学']],
  ['19', '冬夜写作装', ['冬季', '夜晚', '写作']],
  ['20', '冬季城市旅行装', ['冬季', '城市', '旅行']],
  ['21', '米白衬衫 + 黑色吊带连衣裙', ['叠穿', '连衣裙']],
  ['22', '深炭灰短袖 T + 黑色百慕大短裤', ['夏季', '短袖', '日常']],
  ['23', '黑色无袖背心 + 马面裙', ['夏季', '无袖', '马面裙', '新中式', '黑色穿搭']],
  ['24', '白色无袖背心 + 马面裙', ['夏季', '无袖', '马面裙', '新中式', '白色穿搭']],
  ['25', '黑色无袖 + 工装裤', ['夏季', '无袖', '工装', '日常', '黑色穿搭']],
  ['26', '黑色棒球帽运动日常', ['夏季', '运动', '日常', '棒球帽', '黑色穿搭']],
  ['27', '雾蓝灰棒球帽湖边旅行', ['夏季', '旅行', '湖边', '棒球帽', '冷色穿搭']],
  ['28', '深炭灰针织帽冬日通学', ['冬季', '通学', '针织帽', '冷色穿搭']],
  ['29', '冷灰渔夫帽历史旅行', ['旅行', '历史', '渔夫帽', '冷色穿搭']],
  ['30', '黑色贝雷帽博物馆阅读', ['博物馆', '阅读', '贝雷帽', '黑色穿搭']],
] as const

const kiroLifeMedia: MediaAsset[] = kiroLifeLooks.map(([number, title, tags], index) => ({
  id: `kk-life-${number}`,
  characterId: 'kiro',
  type: 'image',
  title,
  caption: `Kiro 的「${title}」生活穿搭记录。`,
  tags: ['Kiro', '生活穿搭', 'v1.1', ...tags],
  visibility: 'public',
  role: 'gallery',
  sortOrder: index + 5,
  source: '生成式视觉素材',
  publicUrl: `/media/kk/life/${number}.webp?v=1.1`,
  createdAt: Number(number) >= 26 ? '2026-09-06' : '2026-09-04',
}))

export const seedProject: NovelProject = {
  dataVersion: 6,
  title: '雾都来信',
  subtitle: '一座城市忘记名字之前，所有人都收到了一封信。',
  penName: '未署名的写作者',
  synopsis:
    '永昼历九十七年，送信人林雾在一封没有收件人的信里，看见了自己失踪七年的名字。她沿着废弃的邮路进入北塔，也一步步走进这座城市被人为抹去的记忆。',
  essays: [
    {
      id: 'essay-personal-site',
      slug: 'a-home-that-keeps-growing',
      title: '把个人网站重新当作一个长期项目',
      excerpt: '主页不是一次性交付物，而是一个持续生长的入口。先把真正会长期使用的内容放进来。',
      content: '主页不是一次性交付物，而是一个持续生长的入口。\n\n我希望 Cactus 既能安放已经想清楚的内容，也能保留仍在形成中的痕迹。公开阅读与私密创作并不冲突，只要边界是在数据层真正建立起来的。',
      category: '随笔',
      tags: ['个人网站', '长期主义'],
      status: 'published',
      createdAt: '2026.08.31',
      updatedAt: '2026.08.31',
    },
    {
      id: 'essay-keep-keen',
      slug: 'keep-keen',
      title: 'Keep Keen：在风沙里保持敏锐',
      excerpt: '敏锐不是紧张，热忱也不是喧闹。它们更像是在荒芜中仍愿意辨认方向。',
      content: '敏锐不是紧张，热忱也不是喧闹。\n\nKeep Keen 对我而言，是在复杂环境里仍保留判断，也不让判断消耗掉好奇心。',
      category: '片段',
      tags: ['Keep Keen', '祁珞'],
      status: 'draft',
      createdAt: '2026.08.30',
      updatedAt: '2026.08.30',
    },
  ],
  settings: [
    {
      id: 'setting-fog-city',
      category: '世界',
      title: '雾城',
      summary: '一座依赖记忆燃料维持永昼的环形城市。',
      details: '城内没有真正的夜晚。每到凌晨，北塔会回收居民当日最不重要的一段记忆，转化为维持穹顶的光。',
      tags: ['永昼', '记忆', '主舞台'],
      visibility: 'public',
      stage: 'canonical',
      updatedAt: '今天 10:24',
    },
    {
      id: 'setting-post-road',
      category: '地点',
      title: '旧邮路',
      summary: '地图上已经消失、只有送信人记得的地下道路。',
      details: '邮路连接七个封闭城区。路标会根据行人的记忆改变方向，因此结伴者看到的路线并不相同。',
      tags: ['地下', '旅程'],
      visibility: 'public',
      stage: 'canonical',
      updatedAt: '昨天 22:11',
    },
    {
      id: 'setting-white-letter',
      category: '物件',
      title: '白信',
      summary: '没有邮戳与收件人的信，内容会随阅读者变化。',
      details: '白信由被北塔完整删除的人留下。公开设定中不应暴露它与沈岚的关系。',
      tags: ['核心谜题', '剧透'],
      visibility: 'private',
      stage: 'canonical',
      updatedAt: '8 月 29 日',
    },
  ],
  characters: [
    {
      id: 'kiro',
      name: '祁珞',
      alias: 'KK / 卡卡',
      role: 'Cactus 虚拟身份',
      faction: 'Cactus Archive',
      age: '未设定',
      appearance: '黑发灰眸，常穿黑白结构服装。袖口保留 KK 标记。',
      personality: '沉静、敏锐、慢热；重视边界，也保留对世界的热忱。',
      motivation: '收集碎片、整理问题，守住那些还没有想明白的东西。',
      secret: '祁珞是 Cactus 面向公开世界的唯一虚拟身份。',
      color: '#3f5141',
      visibility: 'public',
      stage: 'canonical',
      updatedAt: '刚刚',
      mediaIds: ['kk-hero', 'kk-portrait', 'kk-face', 'kk-turnaround'],
    },
    {
      id: 'lin-wu',
      name: '林雾',
      alias: '小雾',
      role: '主角 · 送信人',
      faction: '旧邮局',
      age: '24',
      appearance: '短发，常穿深绿色旧制服，左手腕有一圈墨迹。',
      personality: '克制、敏锐，对承诺有近乎固执的责任感。',
      motivation: '找到失踪的姐姐，并证明一个人不会因为无人记得就从未存在。',
      secret: '她其实是姐姐从记忆中分离出的替身。',
      color: '#54705f',
      visibility: 'public',
      stage: 'canonical',
      updatedAt: '12 分钟前',
    },
    {
      id: 'shen-lan',
      name: '沈岚',
      alias: '北塔记录员',
      role: '关键角色 · 档案员',
      faction: '北塔',
      age: '31',
      appearance: '总戴着黑色手套，右眼装有旧式义眼。',
      personality: '温和、疏离，习惯用精确的时间代替情绪。',
      motivation: '让雾城继续运转，直到找到不再牺牲记忆的方法。',
      secret: '白信的真正寄件人，也是林雾姐姐的旧日同盟。',
      color: '#7d6b5b',
      visibility: 'public',
      stage: 'canonical',
      updatedAt: '昨天 20:43',
    },
    {
      id: 'yu-qi',
      name: '余七',
      alias: '七号',
      role: '同伴 · 地图贩子',
      faction: '南市集',
      age: '19',
      appearance: '总背着塞满手绘地图的红色邮包。',
      personality: '话多、乐观，在危险面前有不合时宜的幽默感。',
      motivation: '画出一张不会被记忆改变的地图。',
      secret: '他从未离开过旧邮路，城中的身体只是投影。',
      color: '#af6a4a',
      visibility: 'public',
      stage: 'canonical',
      updatedAt: '8 月 28 日',
    },
    {
      id: 'director-zhou',
      name: '周署长',
      alias: '守灯人',
      role: '对立角色 · 灯塔署长',
      faction: '灯塔署',
      age: '58',
      appearance: '银白长发，制服永远没有褶皱。',
      personality: '冷静、务实，真诚相信少数牺牲能换来城市存续。',
      motivation: '阻止穹顶熄灭，即使代价是抹去更多人。',
      secret: '他保留了每一份被删除的记忆副本。',
      color: '#4d6175',
      visibility: 'private',
      stage: 'canonical',
      updatedAt: '8 月 26 日',
    },
  ],
  relationships: [
    {
      id: 'rel-lin-shen',
      sourceId: 'lin-wu',
      targetId: 'shen-lan',
      label: '互相试探',
      detail: '沈岚知道林雾的来历，却只提供足以让她继续前进的信息。',
      tone: 'neutral',
      visibility: 'public',
    },
    {
      id: 'rel-lin-yu',
      sourceId: 'lin-wu',
      targetId: 'yu-qi',
      label: '旅伴',
      detail: '从互相利用逐渐变成可以交付后背的朋友。',
      tone: 'positive',
      visibility: 'public',
    },
    {
      id: 'rel-shen-zhou',
      sourceId: 'shen-lan',
      targetId: 'director-zhou',
      label: '师生 / 背叛',
      detail: '沈岚曾是周署长最信任的记录员，白信事件后决裂。',
      tone: 'negative',
      visibility: 'private',
    },
    {
      id: 'rel-zhou-lin',
      sourceId: 'director-zhou',
      targetId: 'lin-wu',
      label: '观察对象',
      detail: '周署长需要确认林雾是否具有保存完整记忆的能力。',
      tone: 'hidden',
      visibility: 'private',
    },
  ],
  chapters: [
    { id: 'ch-1', title: '第一章：没有收件人的信', status: 'ready', wordCount: 4280, updatedAt: '今天 09:12', novelId: 'fog-letters', content: '凌晨四点十七分，旧邮局的黄铜投递口响了一声。' },
    { id: 'ch-2', title: '第二章：地图在说谎', status: 'revising', wordCount: 3615, updatedAt: '昨天 23:47', novelId: 'fog-letters', content: '' },
    { id: 'ch-3', title: '第三章：北塔没有第十三层', status: 'draft', wordCount: 1840, updatedAt: '8 月 29 日', novelId: 'fog-letters', content: '' },
  ],
  novels: [
    {
      id: 'fog-letters',
      title: '雾都来信',
      subtitle: '一座城市忘记名字之前，所有人都收到了一封信。',
      synopsis: '永昼历九十七年，送信人林雾在一封没有收件人的信里，看见了自己失踪七年的名字。',
      status: 'drafting',
      visibility: 'public',
      settingIds: ['setting-fog-city', 'setting-post-road', 'setting-white-letter'],
      characterIds: ['lin-wu', 'shen-lan', 'yu-qi', 'director-zhou'],
      relationshipIds: ['rel-lin-shen', 'rel-lin-yu', 'rel-shen-zhou', 'rel-zhou-lin'],
      chapterIds: ['ch-1', 'ch-2', 'ch-3'],
      updatedAt: '今天 09:12',
    },
  ],
  media: [
    {
      id: 'kk-hero', characterId: 'kiro', type: 'image', title: 'Kiro 标准半身像', caption: '新版首页主视觉，突出灰眸与蓝灰发尾。',
      tags: ['Kiro', '半身', 'Hero', 'v1.1'], visibility: 'public', role: 'cover', sortOrder: 1, source: '生成式视觉素材',
      publicUrl: '/media/kk/hero-1200.webp?v=1.1', createdAt: '2026-09-04',
    },
    {
      id: 'kk-portrait', characterId: 'kiro', type: 'image', title: 'Kiro 全身档案照', caption: '新版全身造型与服装比例档案。',
      tags: ['Kiro', '全身', '档案', 'v1.1'], visibility: 'public', role: 'gallery', sortOrder: 2, source: '生成式视觉素材',
      publicUrl: '/media/kk/portrait-960.webp?v=1.1', createdAt: '2026-09-04',
    },
    {
      id: 'kk-face', characterId: 'kiro', type: 'image', title: 'Kiro 标准脸部特写', caption: '新版人物特写、关系图头像与标签页图标来源。',
      tags: ['Kiro', '特写', '头像', 'v1.1'], visibility: 'public', role: 'graph-avatar', sortOrder: 3, source: '生成式视觉素材',
      publicUrl: '/media/kk/face-800.webp?v=1.1', createdAt: '2026-09-04',
    },
    {
      id: 'kk-turnaround', characterId: 'kiro', type: 'image', title: 'Kiro 四视图设定稿', caption: '正面、左侧、背面与右侧的体态、发型及服装设定。',
      tags: ['Kiro', '四视图', '设定稿', 'v1.1'], visibility: 'public', role: 'gallery', sortOrder: 4, source: '生成式视觉素材',
      publicUrl: '/media/kk/turnaround-1800.webp?v=1.1', createdAt: '2026-09-04',
    },
    ...kiroLifeMedia,
  ],
}
