import type { NovelProject } from './types'

export const seedProject: NovelProject = {
  title: '雾都来信',
  subtitle: '一座城市忘记名字之前，所有人都收到了一封信。',
  penName: '未署名的写作者',
  synopsis:
    '永昼历九十七年，送信人林雾在一封没有收件人的信里，看见了自己失踪七年的名字。她沿着废弃的邮路进入北塔，也一步步走进这座城市被人为抹去的记忆。',
  settings: [
    {
      id: 'setting-fog-city',
      category: '世界',
      title: '雾城',
      summary: '一座依赖记忆燃料维持永昼的环形城市。',
      details: '城内没有真正的夜晚。每到凌晨，北塔会回收居民当日最不重要的一段记忆，转化为维持穹顶的光。',
      tags: ['永昼', '记忆', '主舞台'],
      visibility: 'public',
      updatedAt: '今天 10:24',
    },
    {
      id: 'setting-post-road',
      category: '地点',
      title: '旧邮路',
      summary: '地图上已经消失、只有送信人记得的地下道路。',
      details: '邮路连接七个封闭城区。路标会根据行人的记忆改变方向，因此结伴者看到的路线并不相同。',
      tags: ['地下', '旅程'],
      visibility: 'public',
      updatedAt: '昨天 22:11',
    },
    {
      id: 'setting-white-letter',
      category: '物件',
      title: '白信',
      summary: '没有邮戳与收件人的信，内容会随阅读者变化。',
      details: '白信由被北塔完整删除的人留下。公开设定中不应暴露它与沈岚的关系。',
      tags: ['核心谜题', '剧透'],
      visibility: 'private',
      updatedAt: '8 月 29 日',
    },
  ],
  characters: [
    {
      id: 'lin-wu',
      name: '林雾',
      alias: '小雾',
      role: '主角 · 送信人',
      faction: '旧邮局',
      age: '24',
      appearance: '短发，常穿深绿色旧制服，左手腕有一圈墨迹。',
      personality: '克制、敏锐，对承诺有近乎固执的责任感。',
      motivation: '找到失踪的姐姐，并证明一个人不会因为无人记得就从未存在。',
      secret: '她其实是姐姐从记忆中分离出的替身。',
      color: '#54705f',
      visibility: 'public',
      updatedAt: '12 分钟前',
    },
    {
      id: 'shen-lan',
      name: '沈岚',
      alias: '北塔记录员',
      role: '关键角色 · 档案员',
      faction: '北塔',
      age: '31',
      appearance: '总戴着黑色手套，右眼装有旧式义眼。',
      personality: '温和、疏离，习惯用精确的时间代替情绪。',
      motivation: '让雾城继续运转，直到找到不再牺牲记忆的方法。',
      secret: '白信的真正寄件人，也是林雾姐姐的旧日同盟。',
      color: '#7d6b5b',
      visibility: 'public',
      updatedAt: '昨天 20:43',
    },
    {
      id: 'yu-qi',
      name: '余七',
      alias: '七号',
      role: '同伴 · 地图贩子',
      faction: '南市集',
      age: '19',
      appearance: '总背着塞满手绘地图的红色邮包。',
      personality: '话多、乐观，在危险面前有不合时宜的幽默感。',
      motivation: '画出一张不会被记忆改变的地图。',
      secret: '他从未离开过旧邮路，城中的身体只是投影。',
      color: '#af6a4a',
      visibility: 'public',
      updatedAt: '8 月 28 日',
    },
    {
      id: 'director-zhou',
      name: '周署长',
      alias: '守灯人',
      role: '对立角色 · 灯塔署长',
      faction: '灯塔署',
      age: '58',
      appearance: '银白长发，制服永远没有褶皱。',
      personality: '冷静、务实，真诚相信少数牺牲能换来城市存续。',
      motivation: '阻止穹顶熄灭，即使代价是抹去更多人。',
      secret: '他保留了每一份被删除的记忆副本。',
      color: '#4d6175',
      visibility: 'private',
      updatedAt: '8 月 26 日',
    },
  ],
  relationships: [
    {
      id: 'rel-lin-shen',
      sourceId: 'lin-wu',
      targetId: 'shen-lan',
      label: '互相试探',
      detail: '沈岚知道林雾的来历，却只提供足以让她继续前进的信息。',
      tone: 'neutral',
      visibility: 'public',
    },
    {
      id: 'rel-lin-yu',
      sourceId: 'lin-wu',
      targetId: 'yu-qi',
      label: '旅伴',
      detail: '从互相利用逐渐变成可以交付后背的朋友。',
      tone: 'positive',
      visibility: 'public',
    },
    {
      id: 'rel-shen-zhou',
      sourceId: 'shen-lan',
      targetId: 'director-zhou',
      label: '师生 / 背叛',
      detail: '沈岚曾是周署长最信任的记录员，白信事件后决裂。',
      tone: 'negative',
      visibility: 'private',
    },
    {
      id: 'rel-zhou-lin',
      sourceId: 'director-zhou',
      targetId: 'lin-wu',
      label: '观察对象',
      detail: '周署长需要确认林雾是否具有保存完整记忆的能力。',
      tone: 'hidden',
      visibility: 'private',
    },
  ],
  chapters: [
    { id: 'ch-1', title: '第一章：没有收件人的信', status: 'ready', wordCount: 4280, updatedAt: '今天 09:12' },
    { id: 'ch-2', title: '第二章：地图在说谎', status: 'revising', wordCount: 3615, updatedAt: '昨天 23:47' },
    { id: 'ch-3', title: '第三章：北塔没有第十三层', status: 'draft', wordCount: 1840, updatedAt: '8 月 29 日' },
  ],
}
